djangogirls/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
]

practice1/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'))
]

type_test/testers/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'testers'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('questions/', views.regConTester, name='regCon'),
    path('questions2/', views.showQuestions, name='allQuestions'),
    path('conQuestion/', views.conQuestions, name='conQuestion'),
    path('createFeedbacks/', views.createFeedback, name='getFeedback'),
    path('showFeedbackList/', views.getFeedbackList, name='feedbackList'),
]

type_test/type_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testers.urls')),
]

type_test/testers/models.py
from django.db import models


class Tester(models.Model):
    t_name = models.CharField(max_length=100)
    t_answer = models.IntegerField(default=0)

    def __str__(self):
        return self.t_name

class Feedback(models.Model):
    name = models.CharField(max_length=100)
    comment = models.TextField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)

type_test/testers/forms.py
from django.forms import ModelForm
from .models import Feedback

class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        fields = ['id', 'name', 'comment']

type_test/testers/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Tester, Feedback
from .forms import FeedbackForm
# Create your views here.
def index(request):
    return render(request, 'index.html')

def regConTester(request):
    Tester.objects.all().delete()
    name = request.POST['name']
    answer = request.POST['answer']
    qs = Tester(t_name = name, t_answer = answer)
    qs.save()

    return HttpResponseRedirect(reverse('testers:allQuestions'))

def showQuestions(request):
    qs = Tester.objects.all()[0]
    context = {'tester_value': qs}
    return render(request, 'testers/questions.html', context)

def conQuestions(request):
    answer = sum(list(map(int, request.POST.getlist('cb'))))
    qs = Tester(t_answer = answer)
    qs.save()
    context = {'tester': qs}
    return render(request, 'testers/results.html', context)

def createFeedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('testers:feedbackList')
    else:
        form = FeedbackForm()

    return render(request, 'testers/feedbacks.html', {'form': form})

def getFeedbackList(request):
    qs = Feedback.objects.all()
    context = {'feedback_list': qs}
    return render(request, 'testers/recievedfeedback.html', context)

type_test/testers/templates/testers/feedbacks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">저장</button>
        </form>
   </div>
</body>
</html>

type_test/testers/templates/testers/questions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'testers:conQuestion'%}" method="post">
    {% csrf_token %}
        {% if tester_value %}
        <ol>
         <li>
            <p>{{tester_value.t_name}}님.</p></br>
            1<input type="checkbox" name="cb" value="1"></br>
            2<input type="checkbox" name="cb" value="2"></br>
            3<input type="checkbox" name="cb" value="3"></br>
            4<input type="checkbox" name="cb" value="4"></br>
            5<input type="checkbox" name="cb" value="5"></br>
            <input type="submit" name="Register"></br>
         </li>
        </ol>
        {% else %}
            <p>결과가 없습니다.</p>
        {% endif %}
</form>
</body>
</html>

type_test/testers/templates/testers/recievedfeedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
gd
{% if feedback_list %}
    <ol>
    {% for s in feedback_list %}
    <li>
    name : {{s.name}}
    comment : {{s.comment}}
    date : {{s.created_date}}
    </li>
    {% endfor %}
    </ol>
    {% else %}
<p>there is nothing.</p>
    {% endif %}
</body>
</html>

type_test/testers/templates/testers/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<p>테스트 결과</p>
    {% if tester %}
    {{tester.t_name}} 님의 테스트 결과는</br>
    {{tester.t_answer}}점입니다.</br>
		{% else %}
		<p>테스트 항목을 선택하지 않으셨습니다</p>
		{% endif %}
		<a href="{% url 'testers:index' %}">처음으로</a>
        <a href="{% url 'testers:getFeedback' %}">피드백 하기</a>

</body>
</html>